const express = require('express')
const cors = require('cors')
const app = express()
const initAuth = require('./routes/auth')
const categoriesRouter = require('./routes/categories')
const formatsRouter = require('./routes/formats')
const productsRouter = require('./routes/products')
const cartRouter = require('./routes/cart')
const ordersRouter = require('./routes/orders')
const historyRouter = require('./routes/history')
const checkAdminRouter = require('./routes/checkAdmin')
const adminStatsRouter = require('./routes/adminStats')
const ChannelsRouter = require('./routes/channels')
const buyRouter = require('./routes/buy')
const userRouter = require('./routes/user')
const path = require('path')
const balanceRouter = require('./routes/balance');
// const startScheduler = require('./scheduler/complited')

app.use(cors())

app.use(express.json())
//Полчение картинки из папки Bot папки static
app.use(express.static(path.join(__dirname, '../Bot/static')))
app.use('/auth', initAuth)
app.use('/categories', categoriesRouter)
app.use('/formats', formatsRouter)
app.use('/products', productsRouter)
app.use('/cart', cartRouter)
app.use('/orders', ordersRouter)
app.use('/history', historyRouter)
app.use('/check_admin', checkAdminRouter)
app.use('/admin_stats', adminStatsRouter)
app.use('/channels', ChannelsRouter)
app.use('/buy', buyRouter)
app.use('/user', userRouter)

const PORT = process.env.PORT || 3000
app.listen(PORT, () => {
    console.log(`Server is running on port ${PORT}`)
    // startScheduler()
})
