FROM python:3.11-slim

WORKDIR /app

# Копируем requirements.txt в контейнер
COPY requirements.txt .

# Устанавливаем зависимости
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --upgrade pip

# Копируем все файлы бота в рабочую директорию контейнера
COPY . .

# Указываем команду запуска бота
CMD ["python", "main.py"]
